CREATE TABLE IF NOT EXISTS jobs (
  job_id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  status TEXT NOT NULL,
  retries INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS jobs_status_idx ON jobs (status);

ALTER TABLE files
ADD COLUMN IF NOT EXISTS job_id TEXT;

ALTER TABLE files
DROP CONSTRAINT IF EXISTS files_job_id_fk;

ALTER TABLE files
ADD CONSTRAINT files_job_id_fk
FOREIGN KEY (job_id)
REFERENCES jobs(job_id)
ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS files_job_id_idx ON files (job_id);
