ALTER TABLE files
DROP CONSTRAINT IF EXISTS files_job_id_fk;

DROP INDEX IF EXISTS files_job_id_idx;

ALTER TABLE files
DROP COLUMN IF EXISTS job_id;

DROP INDEX IF EXISTS jobs_status_idx;

DROP TABLE IF EXISTS jobs;
